ALTER TABLE PROD_CREDIT_DOC DROP FOREIGN KEY PROD_CREDIT_DOC_ibfk_1;
ALTER TABLE PRODUCT DROP FOREIGN KEY PRODUCT_ibfk_1;
ALTER TABLE A7_FORM CHANGE ID ID VARCHAR(50);
ALTER TABLE FORM_TRANSFER CHANGE ID ID VARCHAR(50);
ALTER TABLE INSURANCE CHANGE ID ID VARCHAR(50);
ALTER TABLE INSURANCE ADD SALE_DATE DATE DEFAULT '1970-01-01' ;
ALTER TABLE INSURANCE ADD SALE_NUM VARCHAR(50) DEFAULT '000-000';
ALTER TABLE POLICY CHANGE ID ID VARCHAR(50);
ALTER TABLE PROD_CREDIT_DOC CHANGE IS_REQUIRED IS_REQUIRED BIT;
ALTER TABLE PRODUCT CHANGE IS_ACTIVE IS_ACTIVE BIT;
ALTER TABLE USER_GROUP_LINK CHANGE groupList_ID groupList_ID VARCHAR(50);
ALTER TABLE USER_GROUP_LINK CHANGE UserProfile_ID UserProfile_ID VARCHAR(50);
ALTER TABLE USER_PROFILE CHANGE BLOCKED BLOCKED BIT;
ALTER TABLE USER_PROFILE CHANGE CHANGE_PASSWORD CHANGE_PASSWORD BIT;
ALTER TABLE USER_PROFILE CHANGE ID ID VARCHAR(50);
ALTER TABLE PROD_CREDIT_DOC
ADD CONSTRAINT FK_PROD_CREDIT_DOC_PRODUCT_ID
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID);
ALTER TABLE PRODUCT
ADD CONSTRAINT FK_PRODUCT_VENDOR_ID
FOREIGN KEY (VENDOR_ID) REFERENCES CONTACT (ID);