ALTER TABLE INSURANCE ADD IS_USED_MOTOR BIT DEFAULT 0 NULL;
ALTER TABLE INSURANCE ADD MOTOR_VIN VARCHAR(50) DEFAULT '000-000';
ALTER TABLE INSURANCE ADD BENEFICIARY VARCHAR(50) DEFAULT NULL;

UPDATE INSURANCE INS
SET INS.BENEFICIARY = (SELECT
                         NAME
                       FROM CONTACT
                       WHERE ID = INS.CLIENT_ID)
WHERE INS.BENEFICIARY IS NULL;

UPDATE INSURANCE
SET COVER_TIME = 0
WHERE COVER_TIME IS NULL;