ALTER TABLE COMPANY_OWNER DROP FOREIGN KEY COMPANY_OWNER_ibfk_1;
ALTER TABLE COMPANY_OWNER DROP FOREIGN KEY COMPANY_OWNER_ibfk_2;
ALTER TABLE CONTACT_EMPLOYEE DROP FOREIGN KEY CONTACT_EMPLOYEE_ibfk_1;
ALTER TABLE CONTACT_EMPLOYEE DROP FOREIGN KEY CONTACT_EMPLOYEE_ibfk_2;
ALTER TABLE LEAD DROP FOREIGN KEY LEAD_ibfk_1;
ALTER TABLE LEAD DROP FOREIGN KEY LEAD_ibfk_2;
ALTER TABLE LEGAL_ENTITY DROP FOREIGN KEY LEGAL_ENTITY_ibfk_1;
ALTER TABLE LEGAL_ENTITY DROP FOREIGN KEY LEGAL_ENTITY_ibfk_2;
ALTER TABLE LEGAL_ENTITY DROP FOREIGN KEY LEGAL_ENTITY_ibfk_3;
ALTER TABLE LEGAL_ENTITY_MOTOR_BRAND DROP FOREIGN KEY LEGAL_ENTITY_MOTOR_BRAND_ibfk_1;
ALTER TABLE LEGAL_ENTITY_PROD_CREDIT DROP FOREIGN KEY LEGAL_ENTITY_PROD_CREDIT_ibfk_1;
ALTER TABLE LEGAL_ENTITY_PROD_CREDIT DROP FOREIGN KEY LEGAL_ENTITY_PROD_CREDIT_ibfk_2;
ALTER TABLE PROD_CREDIT_PERCENT DROP FOREIGN KEY PROD_CREDIT_PERCENT_ibfk_1;
ALTER TABLE PRODUCT_IN_SALE DROP FOREIGN KEY PRODUCT_IN_SALE_ibfk_1;
ALTER TABLE PRODUCT_IN_SALE DROP FOREIGN KEY PRODUCT_IN_SALE_ibfk_2;
ALTER TABLE SALE DROP FOREIGN KEY SALE_ibfk_1;
ALTER TABLE SALE DROP FOREIGN KEY SALE_ibfk_2;
ALTER TABLE SALE_POINT DROP FOREIGN KEY SALE_POINT_ibfk_1;
ALTER TABLE SALE_POINT DROP FOREIGN KEY SALE_POINT_ibfk_2;
ALTER TABLE SALEPOINT_LEGALENTITY DROP FOREIGN KEY SALEPOINT_LEGALENTITY_ibfk_1;
ALTER TABLE SALEPOINT_LEGALENTITY DROP FOREIGN KEY SALEPOINT_LEGALENTITY_ibfk_2;
ALTER TABLE A7_FORM CHANGE ID ID VARCHAR(50);
ALTER TABLE CONTACT CHANGE ID ID VARCHAR(50);
CREATE TABLE Contact_ASSOCIATEBRANDS
(
  Contact_ID      VARCHAR(50),
  ASSOCIATEBRANDS VARCHAR(255)
);
CREATE TABLE Contact_ASSOCIATEREGIONS
(
  Contact_ID       VARCHAR(50),
  ASSOCIATEREGIONS VARCHAR(255)
);
ALTER TABLE CONTACT_CODE CHANGE ID ID VARCHAR(50);
CREATE TABLE CONTACT_PERSON
(
  Contact_ID        VARCHAR(50) NOT NULL,
  associateUsers_ID VARCHAR(50) NOT NULL,
  PRIMARY KEY (Contact_ID, associateUsers_ID)
);
ALTER TABLE FORM_TRANSFER CHANGE ID ID VARCHAR(50);
ALTER TABLE INSURANCE CHANGE ID ID VARCHAR(50);
ALTER TABLE INSURANCE CHANGE IS_USED_MOTOR IS_USED_MOTOR TINYINT;
ALTER TABLE INSURANCE CHANGE MOTOR_VIN MOTOR_VIN VARCHAR(50);
ALTER TABLE INSURANCE CHANGE SALE_DATE SALE_DATE DATE;
ALTER TABLE INSURANCE CHANGE SALE_NUM SALE_NUM VARCHAR(50);
CREATE TABLE Insurance_ASSOCIATEBRANDS
(
  Insurance_ID    VARCHAR(50),
  ASSOCIATEBRANDS VARCHAR(255)
);
CREATE TABLE Insurance_ASSOCIATEREGIONS
(
  Insurance_ID     VARCHAR(50),
  ASSOCIATEREGIONS VARCHAR(255)
);
CREATE TABLE INSURANCE_PERSON
(
  Insurance_ID      VARCHAR(50) NOT NULL,
  associateUsers_ID VARCHAR(50) NOT NULL,
  PRIMARY KEY (Insurance_ID, associateUsers_ID)
);
CREATE TABLE Lead_ASSOCIATEBRANDS
(
  Lead_ID         VARCHAR(50),
  ASSOCIATEBRANDS VARCHAR(255)
);
CREATE TABLE Lead_ASSOCIATEREGIONS
(
  Lead_ID          VARCHAR(50),
  ASSOCIATEREGIONS VARCHAR(255)
);
CREATE TABLE LEAD_PERSON
(
  Lead_ID           VARCHAR(50) NOT NULL,
  associateUsers_ID VARCHAR(50) NOT NULL,
  PRIMARY KEY (Lead_ID, associateUsers_ID)
);
ALTER TABLE PAY_ACCOUNT CHANGE ID ID VARCHAR(50);
ALTER TABLE POLICY CHANGE ID ID VARCHAR(50);
ALTER TABLE PROD_CREDIT_DOC CHANGE IS_REQUIRED IS_REQUIRED TINYINT;
ALTER TABLE PRODUCT CHANGE IS_ACTIVE IS_ACTIVE TINYINT;
CREATE TABLE Sale_ASSOCIATEBRANDS
(
  Sale_ID         VARCHAR(50),
  ASSOCIATEBRANDS VARCHAR(255)
);
CREATE TABLE Sale_ASSOCIATEREGIONS
(
  Sale_ID          VARCHAR(50),
  ASSOCIATEREGIONS VARCHAR(255)
);
CREATE TABLE SALE_PERSON
(
  Sale_ID           VARCHAR(50) NOT NULL,
  associateUsers_ID VARCHAR(50) NOT NULL,
  PRIMARY KEY (Sale_ID, associateUsers_ID)
);
ALTER TABLE USER_GROUP_LINK CHANGE groupList_ID groupList_ID VARCHAR(50);
ALTER TABLE USER_GROUP_LINK CHANGE UserProfile_ID UserProfile_ID VARCHAR(50);
ALTER TABLE USER_PROFILE CHANGE BLOCKED BLOCKED TINYINT;
ALTER TABLE USER_PROFILE CHANGE CHANGE_PASSWORD CHANGE_PASSWORD TINYINT;
ALTER TABLE USER_PROFILE CHANGE ID ID VARCHAR(50);
CREATE TABLE UserProfile_PERMITBRANDS
(
  UserProfile_ID VARCHAR(50),
  PERMITBRANDS   VARCHAR(255)
);
CREATE TABLE UserProfile_PERMITREGIONS
(
  UserProfile_ID VARCHAR(50),
  PERMITREGIONS  VARCHAR(255)
);
CREATE INDEX IX_A7_FORM_FK_A7_FORM_OWNER_ID ON A7_FORM (OWNER_ID);
ALTER TABLE COMPANY_OWNER
ADD CONSTRAINT FK_COMPANY_OWNER_COMPANY_ID
FOREIGN KEY (COMPANY_ID) REFERENCES CONTACT (ID);
ALTER TABLE COMPANY_OWNER
ADD CONSTRAINT FK_COMPANY_OWNER_OWNER_ID
FOREIGN KEY (OWNER_ID) REFERENCES CONTACT (ID);
CREATE INDEX IX_COMPANY_OWNER_FK_COMPANY_OWNER_COMPANY_ID ON COMPANY_OWNER (COMPANY_ID);
CREATE INDEX IX_COMPANY_OWNER_FK_COMPANY_OWNER_OWNER_ID ON COMPANY_OWNER (OWNER_ID);
CREATE INDEX IX_CONTACT_FK_CONTACT_AFFILIATION_ID ON CONTACT (AFFILIATION_ID);
ALTER TABLE Contact_ASSOCIATEBRANDS ADD FOREIGN KEY (Contact_ID) REFERENCES CONTACT (ID);
CREATE INDEX CntctSSOCIATEBRANDSFKCntctASSOCIATEBRANDSContactID ON Contact_ASSOCIATEBRANDS (Contact_ID);
ALTER TABLE Contact_ASSOCIATEREGIONS ADD FOREIGN KEY (Contact_ID) REFERENCES CONTACT (ID);
CREATE INDEX CntctSSCIATEREGIONSFKCntctSSOCIATEREGIONSContactID ON Contact_ASSOCIATEREGIONS (Contact_ID);
CREATE INDEX IX_CONTACT_CODE_FK_CONTACT_CODE_CONTACT_ID ON CONTACT_CODE (CONTACT_ID);
CREATE INDEX CONTACT_EMPLOYEE_FK_CONTACT_EMPLOYEE_EMPLOYEE_ID ON CONTACT_EMPLOYEE (EMPLOYEE_ID);
ALTER TABLE CONTACT_EMPLOYEE
ADD CONSTRAINT FK_CONTACT_EMPLOYEE_CONTACT_ID
FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT (ID);
ALTER TABLE CONTACT_EMPLOYEE
ADD CONSTRAINT FK_CONTACT_EMPLOYEE_EMPLOYEE_ID
FOREIGN KEY (EMPLOYEE_ID) REFERENCES CONTACT (ID);
CREATE INDEX IX_CONTACT_EMPLOYEE_FK_CONTACT_EMPLOYEE_CONTACT_ID ON CONTACT_EMPLOYEE (CONTACT_ID);
ALTER TABLE CONTACT_PERSON ADD FOREIGN KEY (associateUsers_ID) REFERENCES CONTACT (ID);
ALTER TABLE CONTACT_PERSON ADD FOREIGN KEY (Contact_ID) REFERENCES CONTACT (ID);
CREATE INDEX CONTACT_PERSON_FK_CONTACT_PERSON_associateUsers_ID ON CONTACT_PERSON (associateUsers_ID);
CREATE INDEX IX_CONTACT_PERSON_FK_CONTACT_PERSON_Contact_ID ON CONTACT_PERSON (Contact_ID);
CREATE INDEX IX_FORM_TRANSFER_FK_FORM_TRANSFER_FROMCONTACT_ID ON FORM_TRANSFER (FROMCONTACT_ID);
CREATE INDEX IX_FORM_TRANSFER_FK_FORM_TRANSFER_TOCONTACT_ID ON FORM_TRANSFER (TOCONTACT_ID);
CREATE INDEX FORMTRANSFERNUMSFKFORMTRANSFERNUMSFORM_TRANSFER_ID ON FORM_TRANSFER_NUMS (FORM_TRANSFER_ID);
CREATE INDEX IX_INSURANCE_FK_INSURANCE_CLIENT_ID ON INSURANCE (CLIENT_ID);
CREATE INDEX IX_INSURANCE_FK_INSURANCE_DEALER_ID ON INSURANCE (DEALER_ID);
ALTER TABLE Insurance_ASSOCIATEBRANDS ADD FOREIGN KEY (Insurance_ID) REFERENCES INSURANCE (ID);
CREATE INDEX nsrncSSCIATEBRANDSFKnsrncSSOCIATEBRANDSInsuranceID ON Insurance_ASSOCIATEBRANDS (Insurance_ID);
ALTER TABLE Insurance_ASSOCIATEREGIONS ADD FOREIGN KEY (Insurance_ID) REFERENCES INSURANCE (ID);
CREATE INDEX nsrncSSCATEREGIONSFKnsrncSSCIATEREGIONSInsuranceID ON Insurance_ASSOCIATEREGIONS (Insurance_ID);
ALTER TABLE INSURANCE_PERSON ADD FOREIGN KEY (associateUsers_ID) REFERENCES CONTACT (ID);
ALTER TABLE INSURANCE_PERSON ADD FOREIGN KEY (Insurance_ID) REFERENCES INSURANCE (ID);
CREATE INDEX INSURANCE_PERSON_FK_INSURANCE_PERSON_Insurance_ID ON INSURANCE_PERSON (Insurance_ID);
CREATE INDEX INSURANCEPERSONFKINSURANCEPERSON_associateUsers_ID ON INSURANCE_PERSON (associateUsers_ID);
ALTER TABLE LEAD
ADD CONSTRAINT FK_LEAD_CLIENT_ID
FOREIGN KEY (CLIENT_ID) REFERENCES CONTACT (ID);
ALTER TABLE LEAD
ADD CONSTRAINT FK_LEAD_VENDOR_ID
FOREIGN KEY (VENDOR_ID) REFERENCES CONTACT (ID);
CREATE INDEX IX_LEAD_FK_LEAD_CLIENT_ID ON LEAD (CLIENT_ID);
CREATE INDEX IX_LEAD_FK_LEAD_VENDOR_ID ON LEAD (VENDOR_ID);
ALTER TABLE Lead_ASSOCIATEBRANDS ADD FOREIGN KEY (Lead_ID) REFERENCES LEAD (ID);
CREATE INDEX LeadASSOCIATEBRANDSFK_Lead_ASSOCIATEBRANDS_Lead_ID ON Lead_ASSOCIATEBRANDS (Lead_ID);
ALTER TABLE Lead_ASSOCIATEREGIONS ADD FOREIGN KEY (Lead_ID) REFERENCES LEAD (ID);
CREATE INDEX LeadASSOCIATEREGIONSFKLeadASSOCIATEREGIONS_Lead_ID ON Lead_ASSOCIATEREGIONS (Lead_ID);
ALTER TABLE LEAD_PERSON ADD FOREIGN KEY (associateUsers_ID) REFERENCES CONTACT (ID);
ALTER TABLE LEAD_PERSON ADD FOREIGN KEY (Lead_ID) REFERENCES LEAD (ID);
CREATE INDEX IX_LEAD_PERSON_FK_LEAD_PERSON_associateUsers_ID ON LEAD_PERSON (associateUsers_ID);
CREATE INDEX IX_LEAD_PERSON_FK_LEAD_PERSON_Lead_ID ON LEAD_PERSON (Lead_ID);
ALTER TABLE LEGAL_ENTITY
ADD CONSTRAINT FK_LEGAL_ENTITY_COMPANY_ID
FOREIGN KEY (COMPANY_ID) REFERENCES CONTACT (ID);
ALTER TABLE LEGAL_ENTITY
ADD CONSTRAINT FK_LEGAL_ENTITY_DIRECTOR_ID
FOREIGN KEY (DIRECTOR_ID) REFERENCES CONTACT (ID);
ALTER TABLE LEGAL_ENTITY
ADD CONSTRAINT FK_LEGAL_ENTITY_ID
FOREIGN KEY (ID) REFERENCES CONTACT (ID);
CREATE INDEX IX_LEGAL_ENTITY_FK_LEGAL_ENTITY_COMPANY_ID ON LEGAL_ENTITY (COMPANY_ID);
CREATE INDEX IX_LEGAL_ENTITY_FK_LEGAL_ENTITY_DIRECTOR_ID ON LEGAL_ENTITY (DIRECTOR_ID);
ALTER TABLE LEGAL_ENTITY_MOTOR_BRAND
ADD CONSTRAINT FK_LEGAL_ENTITY_MOTOR_BRAND_LegalEntity_ID
FOREIGN KEY (LegalEntity_ID) REFERENCES CONTACT (ID);
CREATE INDEX LGLNTTYMOTORBRANDFKLGLNTITYMOTORBRANDLegalEntityID ON LEGAL_ENTITY_MOTOR_BRAND (LegalEntity_ID);
ALTER TABLE LEGAL_ENTITY_PROD_CREDIT
ADD CONSTRAINT FK_LEGAL_ENTITY_PROD_CREDIT_LEGAL_ENTITY_ID
FOREIGN KEY (LEGAL_ENTITY_ID) REFERENCES CONTACT (ID);
ALTER TABLE LEGAL_ENTITY_PROD_CREDIT
ADD CONSTRAINT FK_LEGAL_ENTITY_PROD_CREDIT_PROD_CREDIT_ID
FOREIGN KEY (PROD_CREDIT_ID) REFERENCES PRODUCT (ID);
CREATE INDEX LGLNTITYPRODCREDITFKLGLNTITYPRODCREDITPRODCREDITID ON LEGAL_ENTITY_PROD_CREDIT (PROD_CREDIT_ID);
CREATE INDEX LGLNTTYPRODCREDITFKLGLNTITYPRODCREDITLEGALENTITYID ON LEGAL_ENTITY_PROD_CREDIT (LEGAL_ENTITY_ID);
CREATE INDEX IX_PAY_ACCOUNT_FK_PAY_ACCOUNT_CONTACT_ID ON PAY_ACCOUNT (CONTACT_ID);
CREATE INDEX IX_PROD_CREDIT_DOC_FK_PROD_CREDIT_DOC_PRODUCT_ID ON PROD_CREDIT_DOC (PRODUCT_ID);
ALTER TABLE PROD_CREDIT_PERCENT
ADD CONSTRAINT FK_PROD_CREDIT_PERCENT_PRODUCT_ID
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID);
CREATE INDEX PRODCREDITPERCENTFK_PROD_CREDIT_PERCENT_PRODUCT_ID ON PROD_CREDIT_PERCENT (PRODUCT_ID);
CREATE INDEX IX_PRODUCT_FK_PRODUCT_VENDOR_ID ON PRODUCT (VENDOR_ID);
ALTER TABLE PRODUCT_IN_SALE
ADD CONSTRAINT FK_PRODUCT_IN_SALE_PRODUCT_ID
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID);
ALTER TABLE PRODUCT_IN_SALE
ADD CONSTRAINT FK_PRODUCT_IN_SALE_SALE_ID
FOREIGN KEY (SALE_ID) REFERENCES SALE (ID);
CREATE INDEX IX_PRODUCT_IN_SALE_FK_PRODUCT_IN_SALE_PRODUCT_ID ON PRODUCT_IN_SALE (PRODUCT_ID);
CREATE INDEX IX_PRODUCT_IN_SALE_FK_PRODUCT_IN_SALE_SALE_ID ON PRODUCT_IN_SALE (SALE_ID);
ALTER TABLE SALE
ADD CONSTRAINT FK_SALE_CLIENT_ID
FOREIGN KEY (CLIENT_ID) REFERENCES CONTACT (ID);
ALTER TABLE SALE
ADD CONSTRAINT FK_SALE_DEALER_ID
FOREIGN KEY (DEALER_ID) REFERENCES CONTACT (ID);
CREATE INDEX IX_SALE_FK_SALE_CLIENT_ID ON SALE (CLIENT_ID);
CREATE INDEX IX_SALE_FK_SALE_DEALER_ID ON SALE (DEALER_ID);
ALTER TABLE Sale_ASSOCIATEBRANDS ADD FOREIGN KEY (Sale_ID) REFERENCES SALE (ID);
CREATE INDEX SaleASSOCIATEBRANDSFK_Sale_ASSOCIATEBRANDS_Sale_ID ON Sale_ASSOCIATEBRANDS (Sale_ID);
ALTER TABLE Sale_ASSOCIATEREGIONS ADD FOREIGN KEY (Sale_ID) REFERENCES SALE (ID);
CREATE INDEX SaleASSOCIATEREGIONSFKSaleASSOCIATEREGIONS_Sale_ID ON Sale_ASSOCIATEREGIONS (Sale_ID);
ALTER TABLE SALE_PERSON ADD FOREIGN KEY (Sale_ID) REFERENCES SALE (ID);
ALTER TABLE SALE_PERSON ADD FOREIGN KEY (associateUsers_ID) REFERENCES CONTACT (ID);
CREATE INDEX IX_SALE_PERSON_FK_SALE_PERSON_associateUsers_ID ON SALE_PERSON (associateUsers_ID);
CREATE INDEX IX_SALE_PERSON_FK_SALE_PERSON_Sale_ID ON SALE_PERSON (Sale_ID);
ALTER TABLE SALE_POINT
ADD CONSTRAINT FK_SALE_POINT_COMPANY_ID
FOREIGN KEY (COMPANY_ID) REFERENCES CONTACT (ID);
ALTER TABLE SALE_POINT
ADD CONSTRAINT FK_SALE_POINT_ID
FOREIGN KEY (ID) REFERENCES CONTACT (ID);
CREATE INDEX IX_SALE_POINT_FK_SALE_POINT_COMPANY_ID ON SALE_POINT (COMPANY_ID);
ALTER TABLE SALEPOINT_LEGALENTITY
ADD CONSTRAINT FK_SALEPOINT_LEGALENTITY_LEGALENTITY_ID
FOREIGN KEY (LEGALENTITY_ID) REFERENCES CONTACT (ID);
ALTER TABLE SALEPOINT_LEGALENTITY
ADD CONSTRAINT FK_SALEPOINT_LEGALENTITY_SALEPOINT_ID
FOREIGN KEY (SALEPOINT_ID) REFERENCES CONTACT (ID);
CREATE INDEX SLPINTLEGALENTITYFKSLPOINTLEGALENTITYLEGALENTITYID ON SALEPOINT_LEGALENTITY (LEGALENTITY_ID);
CREATE INDEX SLPOINTLEGALENTITYFKSLEPOINTLEGALENTITYSALEPOINTID ON SALEPOINT_LEGALENTITY (SALEPOINT_ID);
CREATE INDEX IX_USER_GROUP_LINK_FK_USER_GROUP_LINK_groupList_ID ON USER_GROUP_LINK (groupList_ID);
CREATE INDEX USER_GROUP_LINK_FK_USER_GROUP_LINK_UserProfile_ID ON USER_GROUP_LINK (UserProfile_ID);
CREATE INDEX SERGROUPPERMISSIONFKUSERGROUPPERMISSIONUserGroupID ON USER_GROUP_PERMISSION (UserGroup_ID);
CREATE INDEX IX_USER_PROFILE_FK_USER_PROFILE_CONTACT_ID ON USER_PROFILE (CONTACT_ID);
ALTER TABLE UserProfile_PERMITBRANDS ADD FOREIGN KEY (UserProfile_ID) REFERENCES USER_PROFILE (ID);
CREATE INDEX srPrflPRMITBRANDSFKsrPrflPERMITBRANDSUserProfileID ON UserProfile_PERMITBRANDS (UserProfile_ID);
ALTER TABLE UserProfile_PERMITREGIONS ADD FOREIGN KEY (UserProfile_ID) REFERENCES USER_PROFILE (ID);
CREATE INDEX srPrflPRMTREGIONSFKsrPrflPRMITREGIONSUserProfileID ON UserProfile_PERMITREGIONS (UserProfile_ID);