CREATE TABLE FILE_CONTAINER
(
  ID VARCHAR(50) PRIMARY KEY NOT NULL,
  CREATED_AT DATETIME,
  CREATED_BY VARCHAR(50),
  DESCRIPTION VARCHAR(255),
  FILEDATA LONGBLOB,
  FILESIZE BIGINT,
  MIMETYPE VARCHAR(255),
  MODIFIED_AT DATETIME,
  MODIFIED_BY VARCHAR(50),
  NAME VARCHAR(255),
  OWNER_ID VARCHAR(50),
  VERSION INT
);
ALTER TABLE FILE_CONTAINER ADD FOREIGN KEY ( OWNER_ID ) REFERENCES INSURANCE ( ID );
CREATE INDEX INDEX_FILE_CONTAINER_NAME ON FILE_CONTAINER ( NAME );
CREATE INDEX INDEX_FILE_CONTAINER_OWNER_ID ON FILE_CONTAINER ( OWNER_ID );
CREATE INDEX IX_FILE_CONTAINER_FK_FILE_CONTAINER_OWNER_ID ON FILE_CONTAINER ( OWNER_ID );
