DROP TABLE
  `CONTACT_ASSOCIATEBRANDS`,
  `CONTACT_ASSOCIATEREGIONS`,
  `CONTACT_PERSON`,
  `INSURANCE_ASSOCIATEBRANDS`,
  `INSURANCE_ASSOCIATEREGIONS`,
  `INSURANCE_PERSON`,
  `LEAD_ASSOCIATEBRANDS`,
  `LEAD_ASSOCIATEREGIONS`,
  `LEAD_PERSON`,
  `SALE_ASSOCIATEBRANDS`,
  `SALE_ASSOCIATEREGIONS`,
  `SALE_PERSON`;