DROP TABLE
`Contact_ASSOCIATEBRANDS`,
`Contact_ASSOCIATEREGIONS`,
`CONTACT_PERSON`,
`Insurance_ASSOCIATEBRANDS`,
`Insurance_ASSOCIATEREGIONS`,
`INSURANCE_PERSON`,
`Lead_ASSOCIATEBRANDS`,
`Lead_ASSOCIATEREGIONS`,
`LEAD_PERSON`,
`Sale_ASSOCIATEBRANDS`,
`Sale_ASSOCIATEREGIONS`,
`SALE_PERSON`;