DROP TABLE
`Contact_ASSOCIATEBRANDS`,
`Contact_ASSOCIATEREGIONS`,
`Contact_PERSON`,
`Insurance_ASSOCIATEBRANDS`,
`Insurance_ASSOCIATEREGIONS`,
`Insurance_PERSON`,
`Lead_ASSOCIATEBRANDS`,
`Lead_ASSOCIATEREGIONS`,
`Lead_PERSON`,
`Sale_ASSOCIATEBRANDS`,
`Sale_ASSOCIATEREGIONS`,
`Sale_PERSON`;