INSERT INTO `SALE_MOTOR`
(`ID`,
 `IS_ARCHIVED`,
 `BRAND`,
 `MODEL`,
 `PRICE`,
 `TYPE`,
 `VERSION`,
 `SALE_ID`)
  SELECT
    UUID(),
    0,
    MOTOR_BRAND,
    MOTOR_MODEL,
    MOTOR_PRICE,
    MOTOR_TYPE,
    1,
    ID
  FROM SALE;

INSERT INTO `LEAD_MOTOR`
(`ID`,
 `IS_ARCHIVED`,
 `BRAND`,
 `MODEL`,
 `PRICE`,
 `TYPE`,
 `VERSION`,
 `LEAD_ID`)
  SELECT
    UUID(),
    0,
    MOTOR_BRAND,
    MOTOR_MODEL,
    MOTOR_PRICE,
    MOTOR_TYPE,
    1,
    ID
  FROM LEAD;

ALTER TABLE `SALE`
  DROP COLUMN `MOTOR_TYPE`,
  DROP COLUMN `MOTOR_PRICE`,
  DROP COLUMN `MOTOR_MODEL`,
  DROP COLUMN `MOTOR_BRAND`;

ALTER TABLE `LEAD`
  DROP COLUMN `MOTOR_TYPE`,
  DROP COLUMN `MOTOR_PRICE`,
  DROP COLUMN `MOTOR_MODEL`,
  DROP COLUMN `MOTOR_BRAND`;
