#######################################################################################################################
# Копируем данные в общую таблицу клиентов
# Из физ.лиц
INSERT INTO CLIENT
(`ID`,
 `TYPE`,
 `IS_ARCHIVED`,
 `CREATED_BY`,
 `CREATED_AT`,
 `EMAIL`,
 `MODIFIED_BY`,
 `MODIFIED_AT`,
 `NAME`,
 `CELL_PHONE`,
 `VERSION`,
 `WWW`,
 `CITY`,
 `PERIOD_OF_RESIDENCE`,
 `POST_INDEX`,
 `REALTY_KIND`,
 `REGION`,
 `STREET_BLD`,
 `SECURITY_RULE_ID`)
  (SELECT
     `ID`,
     "P",
     `IS_ARCHIVED`,
     `CREATED_BY`,
     `CREATED_AT`,
     `EMAIL`,
     `MODIFIED_BY`,
     `MODIFIED_AT`,
     `NAME`,
     `CELL_PHONE`,
     `VERSION`,
     `WWW`,
     `CITY`,
     `PERIOD_OF_RESIDENCE`,
     `POST_INDEX`,
     `REALTY_KIND`,
     `REGION`,
     `STREET_BLD`,
     `SECURITY_RULE_ID`
   FROM PERSON);

# Из юр.лиц
INSERT INTO CLIENT
(`ID`,
 `TYPE`,
 `IS_ARCHIVED`,
 `CREATED_BY`,
 `CREATED_AT`,
 `EMAIL`,
 `MODIFIED_BY`,
 `MODIFIED_AT`,
 `NAME`,
 `CELL_PHONE`,
 `VERSION`,
 `WWW`,
 `CITY`,
 `PERIOD_OF_RESIDENCE`,
 `POST_INDEX`,
 `REALTY_KIND`,
 `REGION`,
 `STREET_BLD`,
 `SECURITY_RULE_ID`)
  (SELECT
     `ID`,
     "L",
     `IS_ARCHIVED`,
     `CREATED_BY`,
     `CREATED_AT`,
     `EMAIL`,
     `MODIFIED_BY`,
     `MODIFIED_AT`,
     `NAME`,
     `CELL_PHONE`,
     `VERSION`,
     `WWW`,
     `CITY`,
     `PERIOD_OF_RESIDENCE`,
     `POST_INDEX`,
     `REALTY_KIND`,
     `REGION`,
     `STREET_BLD`,
     `SECURITY_RULE_ID`
   FROM LEGAL_ENTITY);

#######################################################################################################################
# Удаляем общие поля
# из Юр.лиц
ALTER TABLE `LEGAL_ENTITY`
DROP FOREIGN KEY `FK_LEGAL_ENTITY_SECURITY_RULE_ID`;
ALTER TABLE `LEGAL_ENTITY`
DROP INDEX `FK_LEGAL_ENTITY_SECURITY_RULE_ID`;

ALTER TABLE LEGAL_ENTITY DROP COLUMN `IS_ARCHIVED`;
ALTER TABLE LEGAL_ENTITY DROP COLUMN `CREATED_BY`;
ALTER TABLE LEGAL_ENTITY DROP COLUMN `CREATED_AT`;
ALTER TABLE LEGAL_ENTITY DROP COLUMN `EMAIL`;
ALTER TABLE LEGAL_ENTITY DROP COLUMN `MODIFIED_BY`;
ALTER TABLE LEGAL_ENTITY DROP COLUMN `MODIFIED_AT`;
ALTER TABLE LEGAL_ENTITY DROP COLUMN `NAME`;
ALTER TABLE LEGAL_ENTITY DROP COLUMN `CELL_PHONE`;
ALTER TABLE LEGAL_ENTITY DROP COLUMN `VERSION`;
ALTER TABLE LEGAL_ENTITY DROP COLUMN `WWW`;
ALTER TABLE LEGAL_ENTITY DROP COLUMN `CITY`;
ALTER TABLE LEGAL_ENTITY DROP COLUMN `PERIOD_OF_RESIDENCE`;
ALTER TABLE LEGAL_ENTITY DROP COLUMN `POST_INDEX`;
ALTER TABLE LEGAL_ENTITY DROP COLUMN `REALTY_KIND`;
ALTER TABLE LEGAL_ENTITY DROP COLUMN `REGION`;
ALTER TABLE LEGAL_ENTITY DROP COLUMN `STREET_BLD`;
ALTER TABLE LEGAL_ENTITY DROP COLUMN `SECURITY_RULE_ID`;
# из Физ.лиц
ALTER TABLE `PERSON`
DROP FOREIGN KEY `FK_PERSON_SECURITY_RULE_ID`;
ALTER TABLE `PERSON`
DROP INDEX `FK_PERSON_SECURITY_RULE_ID`;

ALTER TABLE PERSON DROP COLUMN `IS_ARCHIVED`;
ALTER TABLE PERSON DROP COLUMN `CREATED_BY`;
ALTER TABLE PERSON DROP COLUMN `CREATED_AT`;
ALTER TABLE PERSON DROP COLUMN `EMAIL`;
ALTER TABLE PERSON DROP COLUMN `MODIFIED_BY`;
ALTER TABLE PERSON DROP COLUMN `MODIFIED_AT`;
ALTER TABLE PERSON DROP COLUMN `NAME`;
ALTER TABLE PERSON DROP COLUMN `CELL_PHONE`;
ALTER TABLE PERSON DROP COLUMN `VERSION`;
ALTER TABLE PERSON DROP COLUMN `WWW`;
ALTER TABLE PERSON DROP COLUMN `CITY`;
ALTER TABLE PERSON DROP COLUMN `PERIOD_OF_RESIDENCE`;
ALTER TABLE PERSON DROP COLUMN `POST_INDEX`;
ALTER TABLE PERSON DROP COLUMN `REALTY_KIND`;
ALTER TABLE PERSON DROP COLUMN `REGION`;
ALTER TABLE PERSON DROP COLUMN `STREET_BLD`;
ALTER TABLE PERSON DROP COLUMN `SECURITY_RULE_ID`;

#######################################################################################################################
# Наводим порядок в страховках
# копируем ссылку на клиена
UPDATE INSURANCE i
SET
  i.CLIENT_ID = i.CLIENT_PP
WHERE i.CLIENT_PP IS NOT NULL;

UPDATE INSURANCE i
SET
  i.CLIENT_ID = i.CLIENT_LE
WHERE i.CLIENT_LE IS NOT NULL;

# удаляем лишнее
ALTER TABLE `INSURANCE`
DROP FOREIGN KEY `FK_INSURANCE_CLIENT_PP`,
DROP FOREIGN KEY `FK_INSURANCE_CLIENT_LE`;
ALTER TABLE `INSURANCE`
DROP COLUMN `CLIENT_PP`,
DROP COLUMN `CLIENT_LE`,
DROP INDEX `FK_INSURANCE_CLIENT_PP`,
DROP INDEX `FK_INSURANCE_CLIENT_LE`;

#######################################################################################################################
# Наводим порядок в лидах
# копируем ссылку на клиена
UPDATE LEAD l
SET
  l.CLIENT = l.CLIENT_ID
WHERE l.CLIENT_ID IS NOT NULL;
# удаляем лишнее
ALTER TABLE LEAD
DROP COLUMN `CLIENT_ID`,
DROP INDEX `IX_LEAD_FK_LEAD_CLIENT_ID`,
DROP INDEX `CLIENT_ID`;

#######################################################################################################################
# Наводим порядок в продажах
# копируем ссылку на клиена
UPDATE SALE s
SET
  s.CLIENT = s.CLIENT_ID
WHERE s.CLIENT_ID IS NOT NULL;
# удаляем лишнее
ALTER TABLE `SALE`
DROP FOREIGN KEY `FK_SALE_CLIENT_ID`;
ALTER TABLE SALE
DROP COLUMN `CLIENT_ID`,
DROP INDEX `CLIENT_ID`;
